#!/usr/bin/env python3
"""Pydgeot

Usage:
  pydgeot commands [-a PATH]
  pydgeot <command> [-a PATH] [<args>...]
  pydgeot -h | --help
  pydgeot --version

Options:
  -h, --help            Show this screen.
  --version             Show version.
  -a PATH, --app PATH   App directory.
"""

if __name__ == '__main__':
    import sys
    from docopt import docopt

    sys.path = sys.path[1:]
    from pydgeot import __version__
    from pydgeot.app import App, AppError, InvalidAppRoot
    from pydgeot.commands import CommandError

    args = docopt(__doc__, version='Pydgeot ' + '.'.join(map(lambda x: str(x), __version__)))

    app = None

    try:
        app = App(args['--app'])
    except (AppError, InvalidAppRoot) as e:
        print(e)
        exit(1)

    if args['commands']:
        args['<command>'] = 'commands'

    if app is not None:
        try:
            app.run_command(args['<command>'], *args['<args>'])
        except (AppError, CommandError) as e:
            print(e)
            exit(2)
        except KeyboardInterrupt:
            pass
